// ð ¯ Auto-generated by tauri-specta. DO NOT EDIT MANUALLY.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Polls the background database initialization task to determine if the UI can begin rendering. */
	checkDbReady: () => typedError<boolean, AppError>(__TAURI_INVOKE("check_db_ready")),
	/**  Initiates the OAuth2 PKCE flow, generating a local TCP listener or using a custom URI scheme. */
	startOauth2Login: (clientId: string, clientSecret: string | null, authUrl: string, tokenUrl: string, scopes: string[], extraAuthParams: ([string, string])[], redirectUri: string | null) => typedError<string, AppError>(__TAURI_INVOKE("start_oauth2_login", { clientId, clientSecret, authUrl, tokenUrl, scopes, extraAuthParams, redirectUri })),
	/**
	 *  Completes the OAuth2 flow by exchanging the authorization code for tokens.
	 * 
	 *  Accepts either a deep-link callback (from the OS custom URI scheme) or falls back
	 *  to waiting on the local TCP listener (for standard localhost redirects).
	 */
	completeOauth2Login: (email: string, clientId: string, clientSecret: string, tokenUrl: string, deepLinkCode: string | null, deepLinkState: string | null) => typedError<string, AppError>(__TAURI_INVOKE("complete_oauth2_login", { email, clientId, clientSecret, tokenUrl, deepLinkCode, deepLinkState })),
	queueEmail: (payload: QueueEmailPayload) => typedError<number | null, AppError>(__TAURI_INVOKE("queue_email", { payload })),
	cancelScheduledEmail: (id: number | null) => typedError<null, AppError>(__TAURI_INVOKE("cancel_scheduled_email", { id })),
	saveDraft: (payload: SaveDraftPayload) => typedError<number | null, AppError>(__TAURI_INVOKE("save_draft", { payload })),
	getDrafts: (accountId: string) => typedError<OutboxMessage[], AppError>(__TAURI_INVOKE("get_drafts", { accountId })),
	getThreadMessages: (threadId: string) => typedError<Message[], AppError>(__TAURI_INVOKE("get_thread_messages", { threadId })),
	deleteDraft: (draftId: number | null) => typedError<null, AppError>(__TAURI_INVOKE("delete_draft", { draftId })),
	/**  Fetches all calendar events for an account across all discovered calendars. */
	getCalendarEvents: (accountId: string) => typedError<CalendarEventRecord[], AppError>(__TAURI_INVOKE("get_calendar_events", { accountId })),
	/**  Fetches all contacts for an account across all discovered address books. */
	getContacts: (accountId: string) => typedError<ContactRecord[], AppError>(__TAURI_INVOKE("get_contacts", { accountId })),
	/**
	 *  Executes a unified full-text search across emails, calendar events, and contacts.
	 * 
	 *  Uses `tokio::join!` to query all three FTS5 virtual tables concurrently.
	 *  Relevance is determined purely by the FTS5 `rank` order (index `i`), not a custom scoring algorithm.
	 */
	unifiedSearch: (query: string, limit: number | null) => typedError<UnifiedSearchItem[], AppError>(__TAURI_INVOKE("unified_search", { query, limit })),
	/**  Discovers IMAP/SMTP settings for an email address using the 4-step fallback chain. */
	discoverEmailSettings: (email: string) => typedError<ProviderConfig, AppError>(__TAURI_INVOKE("discover_email_settings", { email })),
	/**  Creates a new account, securely stores credentials, and migrates OAuth tokens if necessary. */
	addAccount: (payload: AddAccountPayload) => typedError<Account, AppError>(__TAURI_INVOKE("add_account", { payload })),
	listAccounts: () => typedError<Account[], AppError>(__TAURI_INVOKE("list_accounts")),
	/**  Deletes an account and all associated data, recovering from mutex poisoning if necessary. */
	deleteAccount: (accountId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_account", { accountId })),
	getMailboxes: (accountId: string) => typedError<Mailbox[], AppError>(__TAURI_INVOKE("get_mailboxes", { accountId })),
	/**
	 *  Fetches a paginated list of threaded emails.
	 * 
	 *  `before_id` is typed as `f64` in the IPC boundary because Tauri Specta maps `i64` to
	 *  strings or requires BigInt in TypeScript. Using `f64` keeps them as standard JS numbers,
	 *  which is perfectly safe since DB row IDs will never exceed JS's $2^{53}$ precision limit.
	 */
	getEmailsPaginated: (accountId: string, mailboxName: string, beforeId: number | null, pageSize: number) => typedError<Message[], AppError>(__TAURI_INVOKE("get_emails_paginated", { accountId, mailboxName, beforeId, pageSize })),
	/**
	 *  Fetches only the headers, text/html bodies, and small inline images.
	 *  Defers large attachments to on-demand fetching via `fetch_email_attachment`.
	 */
	fetchEmailBody: (accountId: string, mailboxName: string, uid: number) => typedError<IpcParsedEmail, AppError>(__TAURI_INVOKE("fetch_email_body", { accountId, mailboxName, uid })),
	/**  Attempts to load the email body from the local encrypted JSON cache before hitting the network. */
	getCachedEmailBody: (accountId: string, mailboxName: string, uid: number) => typedError<{
	subject: string | null,
	from: string,
	text_body: string | null,
	html_body: string | null,
	attachments: IpcAttachment[],
} | null, AppError>(__TAURI_INVOKE("get_cached_email_body", { accountId, mailboxName, uid })),
	/**
	 *  Applies an action to an email using an "Optimistic UI + Offline Queue" pattern.
	 * 
	 *  The local database is updated immediately for UI responsiveness. The IMAP command is then
	 *  attempted; if it fails (e.g., due to being offline), the action is queued in `pending_actions`
	 *  to be retried by the background sync worker when connectivity is restored.
	 */
	updateEmailState: (accountId: string, mailboxName: string, uid: number, action: string, destMailbox: string | null) => typedError<null, AppError>(__TAURI_INVOKE("update_email_state", { accountId, mailboxName, uid, action, destMailbox })),
	/**  Decrypts an attachment and writes it to a temporary cache directory for external apps. */
	getAttachmentPath: (blobHash: string) => typedError<string, AppError>(__TAURI_INVOKE("get_attachment_path", { blobHash })),
	getAttachmentBase64: (blobHash: string) => typedError<string, AppError>(__TAURI_INVOKE("get_attachment_base64", { blobHash })),
	/**
	 *  Manually triggers an IMAP sync for the current mailbox.
	 * 
	 *  If an FTS5 corruption error is detected during upsert, it intentionally skips auto-healing
	 *  to prevent an infinite retry loop that would lock up the UI thread.
	 */
	checkForNewEmails: (accountId: string, mailboxName: string) => typedError<number, AppError>(__TAURI_INVOKE("check_for_new_emails", { accountId, mailboxName })),
	/**
	 *  Fetches a remote image, validates it for SSRF, and returns it as a base64 data URI.
	 * 
	 *  If the image fails to load, exceeds the size limit, or triggers an SSRF block,
	 *  it returns a 1x1 transparent GIF fallback pixel to prevent broken UI layout.
	 */
	proxyRemoteImage: (url: string) => typedError<string, AppError>(__TAURI_INVOKE("proxy_remote_image", { url })),
	createFolder: (accountId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("create_folder", { accountId, name })),
	deleteFolder: (accountId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_folder", { accountId, name })),
	renameFolder: (accountId: string, oldName: string, newName: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_folder", { accountId, oldName, newName })),
	/**  Opens the OS file explorer to the local log directory for debugging. */
	openLogsFolder: () => typedError<null, AppError>(__TAURI_INVOKE("open_logs_folder")),
	/**
	 *  Fetches partial body payloads for a specific set of UIDs currently visible in the UI viewport.
	 * 
	 *  Uses IMAP partial fetch (`<0.2000`) to grab only the first 2KB of the body,
	 *  drastically reducing bandwidth compared to downloading full headers for snippet generation.
	 */
	fetchViewportSnippets: (accountId: string, mailboxName: string, uids: number[]) => typedError<{ [key in number]: string }, AppError>(__TAURI_INVOKE("fetch_viewport_snippets", { accountId, mailboxName, uids })),
	/**  Updates the sync window and forces the background IMAP worker to reset its UID tracking. */
	updateSyncWindow: (accountId: string, syncWindow: string) => typedError<null, AppError>(__TAURI_INVOKE("update_sync_window", { accountId, syncWindow })),
	/**  Backfills older emails by fetching a specific UID range from the IMAP server. */
	backfillOlderEmails: (accountId: string, mailboxName: string, beforeUid: number, limit: number) => typedError<Message[], AppError>(__TAURI_INVOKE("backfill_older_emails", { accountId, mailboxName, beforeUid, limit })),
	/**  Prompts the user with a native OS save dialog and writes the decrypted attachment to their chosen path. */
	saveAttachmentDialog: (blobHash: string, filename: string) => typedError<boolean, AppError>(__TAURI_INVOKE("save_attachment_dialog", { blobHash, filename })),
	fetchEmailAttachment: (accountId: string, mailboxName: string, uid: number, sectionId: string) => typedError<string, AppError>(__TAURI_INVOKE("fetch_email_attachment", { accountId, mailboxName, uid, sectionId })),
	/**
	 *  Updates the OS-native badge count and window title fallbacks.
	 * 
	 *  Tauri 2 does not yet have a unified native badge API for Windows/Linux taskbars,
	 *  so we mutate the window title as a fallback to show the unread count.
	 */
	updateBadgeCount: () => typedError<null, AppError>(__TAURI_INVOKE("update_badge_count")),
};

/* Types */
export type Account = {
	id: string,
	email: string,
	provider: string,
	imap_host: string,
	imap_port: number,
	smtp_host: string,
	smtp_port: number,
	auth_method: string,
	oauth_client_id: string | null,
	oauth_client_secret: string | null,
	oauth_token_url: string | null,
	sync_window: string,
	created_at: number | null,
};

export type AddAccountPayload = {
	email: string,
	provider: string,
	imapHost: string,
	imapPort: number,
	smtpHost: string,
	smtpPort: number,
	password: string | null,
	authMethod: string,
	oauthClientId: string | null,
	oauthClientSecret: string | null,
	oauthTokenUrl: string | null,
	syncWindow: string | null,
};

/**
 *  The `#[serde(tag = "kind", content = "message")]` attribute ensures the error is
 *  serialized as a discriminated union in TypeScript, allowing the frontend to
 *  pattern-match on `error.kind` rather than parsing string messages.
 */
export type AppError = { kind: "Database"; message: string } | { kind: "Network"; message: string } | { kind: "Auth"; message: string } | { kind: "NotFound"; message: string } | { kind: "System"; message: string } | { kind: "BadRequest"; message: string } | { kind: "Internal"; message: string };

export type CalendarEventRecord = {
	id: number | null,
	calendar_id: number | null,
	uid: string,
	etag: string,
	url: string,
	ical_data: string,
	last_modified: number | null,
};

export type ContactRecord = {
	id: number | null,
	address_book_id: number | null,
	uid: string,
	etag: string,
	url: string,
	vcard_data: string,
	last_modified: number | null,
};

export type Encryption = "None" | "StartTls" | "Tls";

export type IpcAttachment = {
	filename: string | null,
	mime_type: string,
	size: number,
	section_id: string,
	blob_hash: string | null,
};

export type IpcParsedEmail = {
	subject: string | null,
	from: string,
	text_body: string | null,
	html_body: string | null,
	attachments: IpcAttachment[],
};

export type Mailbox = {
	id: number | null,
	account_id: string,
	name: string,
	delimiter: string | null,
	attributes: string,
	uid_validity: number | null,
	uid_next: number | null,
	highest_modseq: number | null,
	unread_count: number | null,
};

export type Message = {
	id: number | null,
	account_id: string,
	mailbox_name: string,
	uid: number,
	subject: string | null,
	sender: string | null,
	date: string | null,
	date_timestamp: number | null,
	flags: string,
	size: number,
	has_attachments: boolean,
	snippet: string | null,
	blob_hash: string | null,
	attachment_names: string | null,
	message_id: string | null,
	in_reply_to: string | null,
	references_json: string | null,
	thread_id: string | null,
	thread_subject: string | null,
	thread_count: number | null,
};

export type OutboxMessage = {
	id: number | null,
	account_id: string,
	status: string,
	retry_count: number,
	last_error: string | null,
	raw_mime: number[],
	envelope_from: string,
	envelope_to: string,
	subject: string | null,
	body: string | null,
	created_at: number | null,
	sent_at: number | null,
	scheduled_for: number | null,
};

export type ProviderConfig = {
	imap: ServerConfig,
	smtp: ServerConfig,
};

export type QueueEmailPayload = {
	accountId: string,
	to: string[],
	cc: string[],
	bcc: string[],
	subject: string,
	rawMimeBase64: string,
	scheduledFor: number | null,
};

export type SaveDraftPayload = {
	accountId: string,
	to: string[],
	cc: string[],
	bcc: string[],
	subject: string,
	body: string,
	rawMimeBase64: string,
	draftId: number | null,
};

export type ServerConfig = {
	host: string,
	port: number,
	encryption: Encryption,
};

export type UnifiedSearchData = { type: "Email"; record: Message } | { type: "CalendarEvent"; record: CalendarEventRecord } | { type: "Contact"; record: ContactRecord };

export type UnifiedSearchItem = {
	item_type: string,
	relevance: number | null,
	timestamp: number | null,
	title: string,
	subtitle: string,
	data: UnifiedSearchData,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

